### ISSUE TITLE
WhatsApp Business

### ISSUE THREAD

**Issue by Qib10** [Rizky878/rzky-multidevice#17]
Bisa kalo di Private Chat, kalo di grup nggak bisa

**Comment by Rizky878** [comment]
tidak ada example error,  ya engga tau bukan dukun, dan bisa saja errornya dari libray baileys

**Comment by Qib10** [comment]
> tidak ada example error, ya engga tau bukan dukun, dan bisa saja errornya dari libray baileys

Error Error: Cannot find module './lib/game'
Require stack:
- /root/aicebot/handler.js
- /root/aicebot/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at handler (/root/aicebot/handler.js:164:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error Error: Cannot find module './lib/game'
Require stack:
- /root/aicebot/handler.js
- /root/aicebot/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at handler (/root/aicebot/handler.js:164:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
